# This is a basic workflow to help you get started with Actions

name: Spammy Workflow

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!!
